### ISSUE TITLE
Double dot extension

### ISSUE THREAD

**Issue by fede1132** [JavaFactoryDev/LightningStorage#18]
**Describe the bug**
When the plugin creates the file add a dot before the extension name for example Rewards.yml became Rewards..yml

**To Reproduce**
Watch my code.

**Expected behavior**
Only one dot.

**Screenshots**

![](https://i.imgur.com/LyVVmMt.png)

![](https://i.imgur.com/2NzRETo.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: OxygenOS 10 Beta 8
 - Browser Opera GX
 - Version I Don't Know

**Additional context**

**Comment by JavaFactoryDev** [comment]
Hello fede1132,

As stated in the wiki you needed to use an extension.
For example, just use "Config" instead of "Config.yml"
LightningStorage will add these extensions manually.

However, I heard about this issue multiple times so it seems like this behavior is unexcepted and will be changed in upcoming builds.

Regards,
Leonhard
